# Generated by Django 6.0.5 on 2026-05-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='annee_creation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taille',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
