# Generated by Django 6.0.5 on 2026-05-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_age_customuser_annee_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoins',
            fields=[
                ('id_besoins', models.AutoField(primary_key=True, serialize=False)),
                ('besoin', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBesoins',
            fields=[
                ('id_user_besoins', models.AutoField(primary_key=True, serialize=False)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.besoins')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'besoin'), name='besoins_entreprises')],
            },
        ),
    ]
