# Generated by Django 6.0.5 on 2026-06-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_besoins_userbesoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anciennete',
            fields=[
                ('id_anciennete', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id_secteur_activite', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('id_taille', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='userbesoins',
            name='besoins_entreprises',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='annee_creation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='anciennete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.anciennete'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secteur_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.secteuractivite'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.statut'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.taille'),
        ),
        migrations.RemoveField(
            model_name='userbesoins',
            name='besoin',
        ),
        migrations.RemoveField(
            model_name='userbesoins',
            name='user',
        ),
        migrations.DeleteModel(
            name='Besoins',
        ),
        migrations.DeleteModel(
            name='UserBesoins',
        ),
    ]
