# Generated by Django 6.0.5 on 2026-06-08 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='reponseAuxBesoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'classe'), name='unique_entreprise_classe')],
                'unique_together': {('entreprise', 'classe')},
            },
        ),
    ]
