# Generated by Django 6.0.5 on 2026-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_reponseauxbesoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
