# Generated by Django 6.0.5 on 2026-06-23 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_classe_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoins',
            fields=[
                ('id_besoins', models.AutoField(primary_key=True, serialize=False)),
                ('libele', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='besoins_entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besoins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.besoins')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'besoins'), name='unique_entreprise_besoins')],
                'unique_together': {('entreprise', 'besoins')},
            },
        ),
        migrations.CreateModel(
            name='offres_entreprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.besoins')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'offres'), name='unique_entreprise_offres')],
                'unique_together': {('entreprise', 'offres')},
            },
        ),
    ]
